---
name: "VGMdb (Self-hosted)"
guid: "d5cbcac9-7bbc-4ae5-a8a2-62e9f392dfeb"
version: 5
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Adds support for VGMdb to music libraries. Can provide both images and metadata for artists and albums."
description: >
  Adds support for VGMdb to music libraries. Can provide both images and metadata for artists and albums.

category: "Music"
artifacts:
  - "Jellyfin.Plugin.Vgmdb.dll"
changelog: |-
  - Jellyfin 10.11 support (#27) @crobibero
